#!/usr/bin/env python

import argparse
import sys

import add_page
import update_page
import view_page
import tree
import list_pages
import list_files
import dump
import create_folder
import add_file
import add_to_module

# modelled after _ _ main _ _.py from
# https://github.com/dib-lab/screed/tree/master/screed
class AllCommands(object):

    def __init__(self):
        parser = argparse.ArgumentParser(
            description="",
            usage='''canvasCourseCli <command> [<args>]

Available:

    list_files    -u URL                        List all files for a course on Canvas.
    list_pages    -u URL                        List all pages for a course on Canvas.
    tree          -u URL                        List all folders for a course on Canvas.
    dump          -u URL                        Download all files and pages for a course on Canvas.
    view_page     -u URL                        View the content of a page on Canvas.
    add_page      -u URL -t TITLE -f HTML_FILE  Add a new page to Canvas.
    create_folder -u URL                        Create a new folder on Canvas.
    add_file      -u URL -f FILE_TO_SEND        Add a file to a folder on Canvas.
    update_page   -u URL -f HTML_FILE           Update the content of a page on Canvas.
    add_to_module -u URL -m MODULE_NAME         Add a page on Canvas to a module.

To get help on individual commands: canvasCourseCli <command> -h

''')

        commands = {
            'add_page': add_page.main,
            'update_page': update_page.main,
            'view_page': view_page.main,
            'tree': tree.main,
            'list_pages': list_pages.main,
            'list_files': list_files.main,
            'dump': dump.main,
            'create_folder': create_folder.main,
            'add_file': add_file.main,
            'add_to_module': add_to_module.main
        }

        parser.add_argument('command')
        args = parser.parse_args(sys.argv[1:2])
        if args.command not in commands:
            print('Unrecognized command')
            parser.print_help()
            sys.exit(1)

        cmd = commands[args.command]
        cmd(sys.argv[2:])


def main():
    AllCommands()
    return 0

if __name__ == "__main__":
    main()
